# Exercise: 
Manually calculate output for the following cases and compare it with system’s output.
1. Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
2. Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

Import necessary libraries.

In [1]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB

Prepare dataset.

In [2]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

Digitize the data set using encoding

In [3]:
#Creating the labelEncoder
le = preprocessing.LabelEncoder()
#Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [4]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


Merge different features to prepare dataset

In [5]:
#Combining the weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


Train 'Naive Bayes Classifier’

In [6]:
#Create a MultinomialNB Classifier
model=MultinomialNB()
#Train the model using the training sets
model.fit(features,label)

#Create a CategoricalNB Classifier
model1 = CategoricalNB()
#Train the model using the training sets
model1.fit(features,label)

#Create a GaussianNB Classifier
model2 = GaussianNB()
#Train the model using the training sets
model2.fit(features,label)

GaussianNB()

Predict Output for new data

In [7]:
#Predict the Output using MultinomialNB Classifier
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

#Predict the Output using CategoricalNB Classifier
predicted= model1.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

#Predict the Output using GaussianNB Classifier
predicted= model2.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]
Predicted Value: [1]


1. Will you play if the temperature is 'Hot' and weather is 'overcast'?

In [8]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

predicted= model1.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

predicted= model2.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]
Predicted Value: [1]


2. Will you play if the temperature is 'Mild' and weather is 'Sunny'?

In [9]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

predicted= model1.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

predicted= model2.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [0]
Predicted Value: [0]


# Exercise

1. Try the algo on Dataset2 - OneHotEncoding of features:
and Train test Division 75%-25%
2. Apply algorithm on wine dataset - LabelEncoding of
features: and Train test Division 80%-20%

1. Try the algo on Dataset2 - OneHotEncoding of features:
and Train test Division 75%-25%

In [10]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from google.colab import drive
import pandas as pd
import numpy as np

dataset = pd.read_csv("/content/drive/MyDrive/SEM-6/ML/Lab-3/Dataset2.csv", na_values= ["??", "????"])
print(dataset)

   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [11]:
print()

X = dataset.iloc[:, :-1].values
# Only last column
Y = dataset.iloc[:, -1].values

print()
print("Features : ")
print(X)
print()
print("Labels : ")
print(Y)

print()
outlook = dataset.iloc[:,0].values
print(outlook)
print()
temp = dataset.iloc[:,1].values
print(temp)
print()
wind=dataset.iloc[:,2].values
print(wind)
print()
humidity = dataset.iloc[:,3].values
print(humidity)



Features : 
[['R' 'H' 'F' 'Normal']
 ['R' 'H' 'T' 'High']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'F' 'Normal']
 ['S' 'M' 'T' 'Low']
 ['O' 'C' 'T' 'Normal']
 ['R' 'C' 'F' 'Normal']
 ['R' 'C' 'F' 'Low']
 ['S' 'M' 'F' 'High']
 ['R' 'M' 'T' 'High']
 ['O' 'M' 'T' 'Low']
 ['O' 'H' 'F' 'Normal']
 ['S' 'M' 'T' 'Normal']]

Labels : 
['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']

['R' 'R' 'O' 'S' 'S' 'S' 'O' 'R' 'R' 'S' 'R' 'O' 'O' 'S']

['H' 'H' 'H' 'M' 'M' 'M' 'C' 'C' 'C' 'M' 'M' 'M' 'H' 'M']

['F' 'T' 'F' 'F' 'F' 'T' 'T' 'F' 'F' 'F' 'T' 'T' 'F' 'T']

['Normal' 'High' 'Normal' 'Normal' 'Normal' 'Low' 'Normal' 'Normal' 'Low'
 'High' 'High' 'Low' 'Normal' 'Normal']


In [12]:
le = preprocessing.LabelEncoder()
outlook_encoded=le.fit_transform(outlook)
print("Outlook:" ,outlook_encoded)

Outlook: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]


In [13]:
temp_encoded=le.fit_transform(temp)
print("Temp:" ,temp_encoded)

Temp: [1 1 1 2 2 2 0 0 0 2 2 2 1 2]


In [14]:
wind_encoded=le.fit_transform(wind)
print("Wind:" ,wind_encoded)

Wind: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [15]:
humidity_encoded=le.fit_transform(humidity)
print("Humidity:" ,humidity_encoded)

Humidity: [2 0 2 2 2 1 2 2 1 0 0 1 2 2]


In [16]:
label_encoded=le.fit_transform(label)
print("Label:",label_encoded)

Label: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [17]:
features=tuple(zip(outlook_encoded,temp_encoded,wind_encoded,humidity_encoded))
print("Features:",features)

Features: ((1, 1, 0, 2), (1, 1, 1, 0), (0, 1, 0, 2), (2, 2, 0, 2), (2, 2, 0, 2), (2, 2, 1, 1), (0, 0, 1, 2), (1, 0, 0, 2), (1, 0, 0, 1), (2, 2, 0, 0), (1, 2, 1, 0), (0, 2, 1, 1), (0, 1, 0, 2), (2, 2, 1, 2))


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics

In [19]:
#Create a MultinomialNB Classifier
mnb = MultinomialNB()
# Train the model using the training sets
mnb.fit(features,label_encoded)

MultinomialNB()

In [20]:
#Predict Output
predicted= mnb.predict([[1, 1, 0, 2]])
print("Predicted Value:", predicted)

Predicted Value: [1]


In [41]:
#Predict Output
predicted= mnb.predict([[1, 2, 2, 0]])
print("Predicted Value:", predicted)

Predicted Value: [1]


In [42]:
#Predict Output
predicted= mnb.predict([[2, 0, 0, 1]])
print("Predicted Value:", predicted)

Predicted Value: [1]


In [21]:
data_train, data_test, target_train, target_test = train_test_split(features,
label_encoded, test_size = 0.10, random_state = 5)

#Create a GaussianNB Classifier
gnb = GaussianNB()
gnb.fit(data_train, target_train)

GaussianNB()

In [22]:
target_pred = gnb.predict(data_test)
print("Predicted Value:", target_pred)

Predicted Value: [1 1]


In [23]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# # Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.0
precision: 0.0
recall: 0.0


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [24]:
#Create a CategoricalNB Classifier
cnb = CategoricalNB()
cnb.fit(data_train, target_train)

CategoricalNB()

In [25]:
target_pred = cnb.predict(data_test)
print("Predicted Value:", target_pred)

Predicted Value: [1 1]


In [26]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.0
precision: 0.0
recall: 0.0


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


2. Apply algorithm on wine dataset - LabelEncoding of
features: and Train test Division 80%-20%

In [27]:
from sklearn.datasets import load_wine
from sklearn.naive_bayes import GaussianNB

wine = load_wine()

x = wine.data
y= wine.target

feature_names = wine.feature_names
target_names = wine.target_names

print("Features :", feature_names)
print("Targets :", target_names)
print("\nFirst 10 rows of X:\n", x[:5])
print()
print(wine.data.shape)

Features : ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Targets : ['class_0' 'class_1' 'class_2']

First 10 rows of X:
 [[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]

(178, 13)


1. Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%

In [28]:
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(wine.data, wine.target, test_size = 0.20, random_state = 10)

**Using GaussianNB Classfier**

In [29]:
import numpy as np

gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the responses for test dataset
target_pred = gnb.predict(data_test)

In [30]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

#Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8888888888888888


In [31]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[10,  0,  0],
       [ 1, 14,  3],
       [ 0,  0,  8]])

In [32]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.90909091 1.         0.72727273]
recall: [1.         0.77777778 1.        ]


**Using MultinomialNB Classifier**

In [33]:
import numpy as np

gnb = MultinomialNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred1 = gnb.predict(data_test)

In [34]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred1))

Accuracy: 0.8333333333333334


In [35]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred1)

array([[ 8,  2,  0],
       [ 1, 14,  3],
       [ 0,  0,  8]])

In [36]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred1, average=None)
recall = recall_score(target_test, target_pred1, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.88888889 0.875      0.72727273]
recall: [0.8        0.77777778 1.        ]


**Using CategoricalNB Classifier**

In [37]:
import numpy as np

gnb = CategoricalNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred2 = gnb.predict(data_test)

In [38]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred2))

Accuracy: 0.8611111111111112


In [39]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred2)

array([[10,  0,  0],
       [ 1, 13,  4],
       [ 0,  0,  8]])

In [40]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred2, average=None)
recall = recall_score(target_test, target_pred2, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.90909091 1.         0.66666667]
recall: [1.         0.72222222 1.        ]
